### ISSUE TITLE
its not an issue actually

### ISSUE THREAD

**Issue by Hari-pyt** [harshita978/Kaggle_Quora_Duplicate_Question#1]
In TCS AI Exop, they asked the probability(a number between 0 and 1 **mentioned in problem statement) of the questions whether they are duplicate or not.
i.e the output value must be float value but you are getting boolean values as output. 
if possible look into it once.
By the way did you have any info about the shortlists declaration dates? if you have any info please shoot a mail to  gharikrishnareddy7696@gmail.com

**Comment by harshita978** [comment]
Thanku for correcting. I'll surely correct the answer precision. Actually the time given by TCS at first was a bit less for a person who didn't knew anything about it.
Actually I mainly focused on getting a better accuracy, but yes your point is right.
I 'Ll change it according to the need.
Well about the results, I haven't got any mail regarding the results neither I have any idea about it. 
Hope to hear it from you, if you receive it. 
Thanks!

**Comment by Hari-pyt** [comment]
Welcome harshita.
Sure, will inform you if I got any information. 
Thanks for the reply
